[project]
name = "FastEP"
version = "0.1.0"
description = "Surrogate EnergyPlus models for fast building energy optimization"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "polars>=1.33.0",
    "scikit-learn>=1.7.1",
    "torch>=2.8.0",
]
